version: '3.3'

services:
  mysql:
    restart: on-failure:5
    image: mysql:5.7
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      TZ: ${TIMEZONE}
  wordpress:
    restart: on-failure:5
    depends_on:
      - mysql
    image: local-wordpress-xdebug
    container_name: local-wordpress-xdebug
    build:
      context: .
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        XDEBUG_MODE: ${XDEBUG_MODE}
        XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
    volumes:
      - ${WORDPRESS_VOLUME}:/var/www/html
      - ./conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASS}
      WORDPRESS_DB_NAME: ${DATABASE}
      WP_DEBUG: ${WP_DEBUG}
      TZ: ${TIMEZONE}
  adminer:
    restart: on-failure:5
    depends_on:
      - mysql
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
  mailhog:
    restart: on-failure:5
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT}:1025
      - ${MAILHOG_WEB_PORT}:8025