version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      TZ: ${TIMEZONE}
  wordpress:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
    image: local-wordpress-xdebug
    container_name: local-wordpress-xdebug
    volumes: 
      - ${WORDPRESS_VOLUME}:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
    restart: on-failure:5
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASS}
      WORDPRESS_DB_NAME: ${DATABASE}
      TZ: ${TIMEZONE}
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
  adminer:
    depends_on:
      - mysql
    image: adminer:latest
    restart: on-failure:5
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
  mailhog:
    image: mailhog/mailhog
    restart: on-failure:5
    ports: 
      - ${MAILHOG_PORT}:1025
      - ${MAILHOG_WEB_PORT}:8025